language: scala
install:
   - cd ..
   - git clone -b scala-2.11-akka-2.3.2-migration https://git@github.com/uzh/signal-collect.git
   - cd $TRAVIS_BUILD_DIR
   - sbt clean assembly
scala:
   - 2.11.1
